# Starting
summon minecraft:interaction ~ ~ ~ {Tags:["glc","gulceos_load.dp"]}
summon minecraft:marker ~ ~ ~ {Tags:["glc"],CustomName:{"text":"Gulce","color":"green","italic":false}}
execute as @e[type=minecraft:interaction,tag=gulceos_load.dp,limit=1] at @s run execute as @e[type=minecraft:marker,tag=glc,limit=1] at @s run say [DP] Loading...
data modify storage custom:storage Starter set value {"type":"starting"}

# Auto-generated by AdminPower editor
scoreboard objectives add ap_clear_weather trigger
scoreboard objectives add ap_feed_self trigger
scoreboard objectives add ap_give_tools trigger

data modify storage custom:storage Starter set value {"type":"loading"}
scoreboard objectives add ap_heal_self trigger
scoreboard objectives add ap_rain_weather trigger
scoreboard objectives add ap_speed_boost trigger
scoreboard objectives add ap_toggle_day trigger
scoreboard objectives add ap_cc trigger
scoreboard objectives add ap_help trigger
scoreboard objectives add ap_update trigger
scoreboard objectives add ap_toggle_night trigger
scoreboard objectives add ap_logs trigger
scoreboard objectives add ap_actions trigger
scoreboard objectives add ap_survival trigger
scoreboard objectives add ap_adventure trigger
scoreboard objectives add ap_spectator trigger
scoreboard objectives add ap_add_xp trigger
scoreboard objectives add ap_kill_all_mobs trigger
scoreboard objectives add ap_run trigger
scoreboard objectives add ap_clear_weather trigger
scoreboard objectives add ap_feed_self trigger
scoreboard objectives add ap_give_tools trigger
scoreboard objectives add ap_lp_menu trigger
scoreboard objectives add ap_creative trigger
scoreboard objectives add ap_main_menu trigger
scoreboard objectives add ap_homeGUI trigger
scoreboard objectives add ap_fill_area trigger
scoreboard objectives add ap_time trigger
scoreboard objectives add ap_gamemode trigger
scoreboard objectives add ap_rain trigger
scoreboard objectives add ap_godarmor trigger
scoreboard objectives add ap_ban trigger
scoreboard objectives add ap_permissions trigger
scoreboard objectives add ap_test trigger
scoreboard objectives add ap_xyz trigger
scoreboard objectives add coords_x dummy
scoreboard objectives add coords_y dummy
scoreboard objectives add coords_z dummy
scoreboard objectives add ap_clear trigger

schedule function custom_admin:load2 2t replace
